### ISSUE TITLE
Get an invoice by id fails if asking for recurringInvoice field

### ISSUE THREAD

**Issue by javiquiros** [siwapp/siwapp#10]
According to:
https://htmlpreview.github.io/?https://github.com/siwapp/siwapp/blob/master/api_docs/public/index.html#tag-Get

The mutation to get an invoice can ask for the recurringInvoice field.

If so, the application breaks:

```
"# Absinthe.SerializationError at POST /graphql\n\nException:\n\n    ** (Absinthe.SerializationError) Could not serialize term #Ecto.Association.NotLoaded<association :recurring_invoice is not loaded> as type ID\n    \n    When serializing the field:\n    Invoice.recurring_invoice (/app/lib/siwapp_web/schema/invoice_types.ex:30)\n    \n        (absinthe 1.7.0) lib/absinthe/phase/document/result.ex:58: Absinthe.Phase.Document.Result.data/2\n        (absinthe 1.7.0) lib/absinthe/phase/document/result.ex:106: Absinthe.Phase.Document.Result.field_data/3\n        (absinthe 1.7.0) lib/absinthe/phase/document/result.ex:22: Absinthe.Phase.Document.Result.process/1\n        (absinthe 1.7.0) lib/absinthe/phase/document/result.ex:11: Absinthe.Phase.Document.Result.run/2\n        (absinthe 1.7.0) lib/absinthe/pipeline.ex:384: Absinthe.Pipeline.run_phase/3\n        (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4\n        (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2\n        (phoenix 1.6.6) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2\n        (siwapp 0.1.0) lib/siwapp_web/endpoint.ex:1: SiwappWeb.Endpoint.plug_builder_call/2\n        (siwapp 0.1.0) lib/siwapp_web/endpoint.ex:1: SiwappWeb.Endpoint.\"call (overridable 3)\"/2\n        (siwapp 0.1.0) lib/plug/debugger.ex:136: SiwappWeb.Endpoint.\"call (overridable 4)\"/2\n        (siwapp 0.1.0) lib/siwapp_web/endpoint.ex:1: SiwappWeb.Endpoint.call/2\n        (phoenix 1.6.6) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4\n        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2\n        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3\n        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3\n        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n    \n\n## Connection details\n\n### Params\n\n    %{\"operationName\" => \"invoice\", \"query\" => \"query invoice($id: ID!){\\n  invoice(id: $id){\\n    contactPerson\\n    currency\\n    customerId\\n    draft\\n    dueDate\\n    email\\n    failed\\n    grossAmount\\n    id\\n    identification\\n    insertedAt\\n    invoicingAddress\\n    issueDate\\n    name\\n    netAmount\\n    notes\\n    number\\n    paid\\n    paidAmount\\n    recurringInvoice\\n  }\\n}\", \"variables\" => %{\"id\" => 1}}\n\n### Request info\n\n  * URI: http://localhost:4000/graphql\n  * Query string: \n\n### Headers\n  \n  * accept: application/json\n  * accept-encoding: gzip, deflate, br\n  * accept-language: es,en-GB;q=0.7,en;q=0.3\n  * connection: keep-alive\n  * content-length: 407\n  * content-type: application/json\n  * cookie: csrftoken=3cy9Or86FPy4H2jy9ehtD5ewsEP7L4o85P1BbkVL6mCSyT9sCjufNks0L2ImkFRF; 
```

**Comment by cdelafuen** [comment]
Addressed internally in https://github.com/doofinder/siwapp-deploy/issues/17
