### ISSUE TITLE
global settings is not working

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#261]
https://siwapp-demo.herokuapp.com/settings/global

**Comment by peillis** [comment]
Add some tests too

**Comment by kshitijb** [comment]
@peillis Yep, it is not working for me either. Have you resolved it?

**Comment by peillis** [comment]
not yet

**Comment by kshitijb** [comment]
This is what my log says.

```shell
2017-03-14T16:39:56.645725+00:00 app[web.1]:   Rendered settings/global.html.haml within layouts/application (1.2ms)
2017-03-14T16:39:56.645852+00:00 app[web.1]: Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.7ms)
2017-03-14T16:39:56.646799+00:00 app[web.1]: 
2017-03-14T16:39:56.646800+00:00 app[web.1]: ActionView::Template::Error (undefined method `company_name' for #<GlobalSettings:0x007f89c3899f28>):
2017-03-14T16:39:56.646800+00:00 app[web.1]:     14: 
2017-03-14T16:39:56.646801+00:00 app[web.1]:     15:       .form-group
2017-03-14T16:39:56.646802+00:00 app[web.1]:     16:         = f.label :company_name, "Company Name:"
2017-03-14T16:39:56.646803+00:00 app[web.1]:     17:         = f.text_field :company_name, class: 'form-control'
2017-03-14T16:39:56.646803+00:00 app[web.1]:     18:       .form-group
2017-03-14T16:39:56.646803+00:00 app[web.1]:     19:         = f.label :company_vat_id, "Company VAT ID:"
2017-03-14T16:39:56.646804+00:00 app[web.1]:     20:         = f.text_field :company_vat_id, class: 'form-control'
2017-03-14T16:39:56.646805+00:00 app[web.1]:   app/views/settings/global.html.haml:17:in `block in _app_views_settings_global_html_haml__3408517872034956912_70114335350260'
2017-03-14T16:39:56.646806+00:00 app[web.1]:   app/views/settings/global.html.haml:5:in `_app_views_settings_global_html_haml__3408517872034956912_70114335350260'
```

**Comment by chavenor** [comment]
Did anyone get this working?  I spent a lot of time today trying to figure out how override or change them but I can't seem to figure it out.  

I'm trying to send out some emails and am unable to figure out where these settings reside or how to change them.   

An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.

**Comment by chavenor** [comment]
@peillis 

I made the changes to each file in the last merge. 

Getting the following error.  When trying to access the ```SMTP``` and the ```GLOBAL``` settings.

```
14:25:02.861385+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=campuslists-billing.herokuapp.com request_id=dcc30a31-745
-efbd04636530 fwd="97.94.37.226" dyno=web.1 connect=0ms service=1ms status=200 bytes=188 protocol=https
14:25:06.048501+00:00 heroku[router]: at=info method=GET path="/settings/global" host=campuslists-billing.herokuapp.com request_id=f9a7c0a1
9f8d-f404f19182d9 fwd="97.94.37.226" dyno=web.1 connect=0ms service=8ms status=500 bytes=1714 protocol=https
14:25:06.045169+00:00 app[web.1]: Started GET "/settings/global" for 97.94.37.226 at 2017-04-22 14:25:06 +0000
14:25:06.048537+00:00 app[web.1]: Processing by SettingsController#global as HTML
14:25:06.050142+00:00 app[web.1]:   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
14:25:06.050856+00:00 app[web.1]: Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.6ms)
14:25:06.051623+00:00 app[web.1]:
14:25:06.051624+00:00 app[web.1]: NoMethodError (undefined method `each' for nil:NilClass):
14:25:06.051624+00:00 app[web.1]:   lib/siwapp_settings.rb:10:in `initialize'
14:25:06.051625+00:00 app[web.1]:   app/controllers/settings_controller.rb:7:in `new'
14:25:06.051625+00:00 app[web.1]:   app/controllers/settings_controller.rb:7:in `global'
14:25:06.051626+00:00 app[web.1]:
14:25:06.051626+00:00 app[web.1]:
14:25:19.223835+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=campuslists-billing.herokuapp.com request_id=72c87ba0-afb
-bfce12aae15f fwd="97.94.37.226" dyno=web.1 connect=1ms service=1ms status=304 bytes=93 protocol=https
14:25:25.895587+00:00 heroku[router]: at=info method=GET path="/settings/smtp" host=campuslists-billing.herokuapp.com request_id=17cdd23c-1
90-b5e9876e4139 fwd="97.94.37.226" dyno=web.1 connect=0ms service=6ms status=500 bytes=1714 protocol=https
14:25:25.893820+00:00 app[web.1]: Started GET "/settings/smtp" for 97.94.37.226 at 2017-04-22 14:25:25 +0000
14:25:25.895501+00:00 app[web.1]: Processing by SettingsController#smtp as HTML
14:25:25.896905+00:00 app[web.1]:   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
14:25:25.897796+00:00 app[web.1]: Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.7ms)
14:25:25.898804+00:00 app[web.1]:
14:25:25.898806+00:00 app[web.1]: NoMethodError (undefined method `each' for nil:NilClass):
14:25:25.898807+00:00 app[web.1]:   lib/siwapp_settings.rb:10:in `initialize'
14:25:25.898807+00:00 app[web.1]:   app/controllers/settings_controller.rb:23:in `new'
14:25:25.898808+00:00 app[web.1]:   app/controllers/settings_controller.rb:23:in `smtp'
14:25:25.898809+00:00 app[web.1]:
14:25:25.898809+00:00 app[web.1]:
```

**Comment by peillis** [comment]
mmm, are you sure you made the changes of the 2 commits? That error looks like the second commit is not applied.

**Comment by chavenor** [comment]
This is the one I updated my files too. 

https://github.com/siwapp/siwapp/commit/34683d6c5537b3f7ef55c7544741f49895898225

**Comment by peillis** [comment]
you missed this then: https://github.com/siwapp/siwapp/commit/b4bbac3f1d97cb3bfadaebb11ec1a1c717943b21

**Comment by chavenor** [comment]
Taking a look.

**Comment by chavenor** [comment]
SMTP Settings are now working.

The globals are tossing the following error...  


```

2017-04-22T15:19:11.240484+00:00 app[web.1]: Completed 500 Internal Server Error in 7ms (ActiveRecord: 3.5ms)
2017-04-22T15:19:11.241483+00:00 app[web.1]:
2017-04-22T15:19:11.241485+00:00 app[web.1]: Psych::SyntaxError ((<unknown>): found unexpected end of stream while scanning a quoted scalar at line 1
column 5):
2017-04-22T15:19:11.241486+00:00 app[web.1]:   lib/siwapp_settings.rb:11:in `block in initialize'
2017-04-22T15:19:11.241486+00:00 app[web.1]:   lib/siwapp_settings.rb:9:in `each'
2017-04-22T15:19:11.241487+00:00 app[web.1]:   lib/siwapp_settings.rb:9:in `initialize'
2017-04-22T15:19:11.241488+00:00 app[web.1]:   app/controllers/settings_controller.rb:7:in `new'
2017-04-22T15:19:11.241488+00:00 app[web.1]:   app/controllers/settings_controller.rb:7:in `global'
2017-04-22T15:19:11.241489+00:00 app[web.1]:
```

```ruby 
module SiwappSettings
  class Base
    include ActiveModel::Model

    class << self; attr_accessor :keys end
    @keys = []

    def initialize(attributes={})
      self.class.keys.each do |key|
        class_eval { attr_accessor key }
        send "#{key}=", attributes[key] || Settings[key]
      end
    end

    def save_settings
      if valid?
        self.class.keys.each do |key|
          Settings[key] = send key
        end
        true
      else
        false
      end
    end

  end
end
```

**Comment by chavenor** [comment]
I was able to fix it.   Bad data in the DB that was bumping out the error.  Many thanks!   
Do you guys have a donation box or something -- great product! 

Casey

**Comment by peillis** [comment]
I'm glad you like it. Collaboration it's our only donation right now :)
